### ISSUE TITLE
What are the meanings of seeds when editing images?

### ISSUE THREAD

**Issue by picksh** [stylegan-human/StyleGAN-Human#15]
Hi, thanks for your great job and the released codes. 

When I tried to edit the images I found that there are some seeds should be fed into the model, e.g. [60948,60965,61174,61210,61511,61598,61610] #bottom -> long.
What are the meanings of these seeds and how to obtain the corresponding seeds if I would like to perform other kinds of editing?

Thank you for your help.

**Comment by stylegan-human** [comment]
Hi, 
The seeds are just random numbers, and you can replace them with any other values. 
Editing with various attributes requires different latent directions. These directions are obtained by a classifier with annotated attributes of input images. Currently, we only provide length changing of upper and bottom clothes (which can be defined by '--attr_name'). For different kinds of editing, you should annotate the corresponding attributes with a batch of images and follow the official repo of InterfaceGAN, Stylespace, and SeFa to generate desired latent directions first.

**Comment by picksh** [comment]
It is clear. Thanks for your reply!
