### ISSUE TITLE
PTI weights 

### ISSUE THREAD

**Issue by nourgana** [stylegan-human/StyleGAN-Human#16]
Hi, 
where can I find pretrained PTI weights for inverting full-human body images into the latent space ? tx

**Comment by leeskyed** [comment]
Hi,
We can provide the pre-trained weights for e4e. It inverts the input image to W/W+ latent codes that can be used as initialization for PTI. PTI starts with the inverted latent codes and fine-tunes the generator network for each specific image.

Code cleanup is still in progress and I think it will be released in two weeks.

**Comment by stylegan-human** [comment]
Hi, we just upload the PTI weight, please have a look.

**Comment by nourgana** [comment]
thanks for that. is it possible to edit on pti outputs?

**Comment by leeskyed** [comment]
I’m closing this issue because it has been inactive for nearly a month. Please reopen if you still encounter this issue. :)

Thank you!
