### ISSUE TITLE
Issue with new release

### ISSUE THREAD

**Issue by Lakshmanaraja** [stylegan-human/StyleGAN-Human#17]
Thanks for releasing Inversion script.  Projection is working fine but the result is poor.  We can try hyper parameter tuning. But you have given another option e4e. ( w+) . It is failing "key error" 

_File "/StyleGAN_Human/pti/training/coaches/base_coach.py", line 136, in initilize_e4e
    opts = ckpt['opts']
KeyError: 'opts'_

I tried printing the key values in ckpt ( loading the e4ew+.pt) .  There is no such key "opts". Could you please tell us what can be done to get e4e based inversion ?  I expect it will give better output than projection.

**Comment by stylegan-human** [comment]
Hi, I double checked the script and the model, but I cannot reproduce this error. Can you tell us more about your current settings? 
btw the weight should come from this link: [e4e_w+.pt](https://drive.google.com/file/d/1NUfSJqLhsrU7c9PwAtlZ9xtrxhzS_6tu/view?usp=sharing).

**Comment by leeskyed** [comment]
I’m closing this issue because it has been inactive for nearly a month. Please reopen if you still encounter this issue. :)

Thank you!
