### ISSUE TITLE
Bad link for stylegan_human_v3_512.pkl

### ISSUE THREAD

**Issue by KyriaAnnwyn** [stylegan-human/StyleGAN-Human#2]
The link is https://github.com/stylegan-human/StyleGAN-Human/blob/main for the pkl

**Comment by wywu** [comment]
Fixed. 
Please have a look :-)
https://drive.google.com/file/d/1_274jk_N6WSCkKWeu7hjHycqGvbuOFf5/view

**Comment by KyriaAnnwyn** [comment]
@wywu Great! Thank you
