### ISSUE TITLE
Improve speed of PTI encoding

### ISSUE THREAD

**Issue by onyekaokonji** [stylegan-human/StyleGAN-Human#21]
Thank you for releasing the codes for PTI encoding of whole body images. I will like to know if there's a way to speed up the process of PTI encoding.

**Comment by johndpope** [comment]
maybe raise issue here https://github.com/danielroich/PTI with @danielroich

**Comment by onyekaokonji** [comment]
Opted for ReStyle encoder. Thanks anyways!
