### ISSUE TITLE
VERY NICE!  How to use custom faces and bodies in insetgan？

### ISSUE THREAD

**Issue by ApologizeLJ** [stylegan-human/StyleGAN-Human#3]
How to use custom faces and bodies for stitching in insetgan

**Comment by stylegan-human** [comment]
We are cleaning the inversion script for real faces and bodies in the InsetGAN pipeline and plan to release it this month. Before that, you can obtain the latent codes of your custom face and body images using PTI, and replace them in [insetgan.py](https://github.com/stylegan-human/StyleGAN-Human/blob/8d6ec642ddc72423c2f0e04c34087dab5ba3bfd4/insetgan.py#L360,https://github.com/stylegan-human/StyleGAN-Human/blob/8d6ec642ddc72423c2f0e04c34087dab5ba3bfd4/insetgan.py#L366).

**Comment by leeskyed** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue. :)

Thank you!

**Comment by youngstu** [comment]
> We are cleaning the inversion script for real faces and bodies in the InsetGAN pipeline and plan to release it this month. Before that, you can obtain the latent codes of your custom face and body images using PTI, and replace them in [insetgan.py](https://github.com/stylegan-human/StyleGAN-Human/blob/8d6ec642ddc72423c2f0e04c34087dab5ba3bfd4/insetgan.py#L360,https://github.com/stylegan-human/StyleGAN-Human/blob/8d6ec642ddc72423c2f0e04c34087dab5ba3bfd4/insetgan.py#L366).

I also use custome real faces and bodys in insetgan. 
When will the inversion script for real faces and bodies be released？ Thanks.
