### ISSUE TITLE
Distorted faces and distorted patterns when using PTI

### ISSUE THREAD

**Issue by resa-git** [stylegan-human/StyleGAN-Human#37]
I tried two methods in order to find the latent code with your pre-trained model, stylegan_human_v2_1024.pkl and e4e_w+.pt

1 - I started with some seeds (e.g. 0, 4000, 4050, 4020, 5500, 5000, 10) and generated some images. Then I treated those images as real images and tried to find their latent representations using ("python run_pti.py"), I used the default config in "pti_configs" folder.  In some cases, the face, and in others, the pattern of the cloth is distorted (please see the following pictures)

 2 - I downloaded the sample images from your GitHub and did the same procedure. The aforementioned problems are more noticeable. I got distorted faces and patterns.

I was wondering if you have any advice for these cases.

![1](https://user-images.githubusercontent.com/42516074/200571978-d9cd868d-7ca7-4951-82f1-17d319f5b307.png)
![2](https://user-images.githubusercontent.com/42516074/200572054-eab31824-eb6d-4743-8d11-5b6a04c1625b.png)

**Comment by resa-git** [comment]
It seems that the quality gets much better if we change the hyperparameters

**Comment by yummyJade** [comment]
> It seems that the quality gets much better if we change the hyperparameters

Hi, I got the same distorted results like yours, I wonder what hyperparameters you adjusted? thank you~

**Comment by resa-git** [comment]
I changed max_pti_steps and LPIPS_value_threshold.
