### ISSUE TITLE
FID of the StyleGAN model 

### ISSUE THREAD

**Issue by betterze** [stylegan-human/StyleGAN-Human#4]
Dear StyleGAN-Human team, 

Thank you for sharing this great work, I really like it. 

Could you upload the FID of each StyleGAN model? Have you try to use the [projected gan](https://github.com/autonomousvision/projected_gan) or [vision-aided-gan](https://github.com/nupurkmr9/vision-aided-gan) to improve the generation quality? 

Thank you for your help.

Best Wishes,

Zongze

**Comment by stylegan-human** [comment]
FID updated, please have a look. We didn't modify the overall architectures since this work is data-centric.

**Comment by betterze** [comment]
Thank you for your reply. I really appreciate it.
