### ISSUE TITLE
alignment.py AttributeError: 'numpy.ndarray' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Zebraslive** [stylegan-human/StyleGAN-Human#42]
I'm having trouble running alignment on dataset. I can't seem to everything setup to make it run. I've got all models and export models in correct folders.
Can someone please tell me what this issue might be?
```
parsing arguments
Num of dataloader :  197
  0% 0/197 [00:00<?, ?it/s]Processing '12037101_016_cdb6'.
  0% 0/197 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "alignment.py", line 221, in <module>
    run(cmd_args)
  File "alignment.py", line 144, in run
    comb, segmentation, bg, ori_img = human_seg.run(image,None)  #mybg) 
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 100, in run
    processed_imgs, ori_shapes = self.preprocess(img)
  File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 92, in preprocess
    processed_img = self.compose(img)[0]
  File "/usr/local/lib/python3.8/dist-packages/paddleseg/transforms/transforms.py", line 60, in __call__
    if 'img' not in data.keys():
AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```

Could we get a colab notebook with alignment configured? I suck at python. I'm a Node.js guy.

**Comment by zhanghongyong123456** [comment]
> : 'numpy.ndarray' o



> I'm having trouble running alignment on dataset. I can't seem to everything setup to make it run. I've got all models and export models in correct folders. Can someone please tell me what this issue might be?
> 
> ```
> parsing arguments
> Num of dataloader :  197
>   0% 0/197 [00:00<?, ?it/s]Processing '12037101_016_cdb6'.
>   0% 0/197 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "alignment.py", line 221, in <module>
>     run(cmd_args)
>   File "alignment.py", line 144, in run
>     comb, segmentation, bg, ori_img = human_seg.run(image,None)  #mybg) 
>   File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 100, in run
>     processed_imgs, ori_shapes = self.preprocess(img)
>   File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 92, in preprocess
>     processed_img = self.compose(img)[0]
>   File "/usr/local/lib/python3.8/dist-packages/paddleseg/transforms/transforms.py", line 60, in __call__
>     if 'img' not in data.keys():
> AttributeError: 'numpy.ndarray' object has no attribute 'keys'
> ```
> 
> Could we get a colab notebook with alignment configured? I suck at python. I'm a Node.js guy.

I guess paddleseg [versions] is too high. Try installing paddleseg  2.5  versions

**Comment by Zebraslive** [comment]
> > : 'numpy.ndarray' o
> 
> > I'm having trouble running alignment on dataset. I can't seem to everything setup to make it run. I've got all models and export models in correct folders. Can someone please tell me what this issue might be?
> > ```
> > parsing arguments
> > Num of dataloader :  197
> >   0% 0/197 [00:00<?, ?it/s]Processing '12037101_016_cdb6'.
> >   0% 0/197 [00:00<?, ?it/s]
> > Traceback (most recent call last):
> >   File "alignment.py", line 221, in <module>
> >     run(cmd_args)
> >   File "alignment.py", line 144, in run
> >     comb, segmentation, bg, ori_img = human_seg.run(image,None)  #mybg) 
> >   File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 100, in run
> >     processed_imgs, ori_shapes = self.preprocess(img)
> >   File "/content/StyleGAN-Human/PP_HumanSeg/deploy/infer.py", line 92, in preprocess
> >     processed_img = self.compose(img)[0]
> >   File "/usr/local/lib/python3.8/dist-packages/paddleseg/transforms/transforms.py", line 60, in __call__
> >     if 'img' not in data.keys():
> > AttributeError: 'numpy.ndarray' object has no attribute 'keys'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could we get a colab notebook with alignment configured? I suck at python. I'm a Node.js guy.
> 
> I guess paddleseg [versions] is too high. Try installing paddleseg 2.5 versions

Thank you!! That fixed it.
